In [15]:
import pandas as pd

tob = pd.read_csv('./tob_question_cluster.csv', index_col='index')

tob.head()

,user,question,question_class,question_cluster,answer_v1,answer_v2,v1_x_v2
index,,,,,,,
0,100,hi,Greet,196,"Hello, how are you?",Hi,0.618338
1,100,Simone,Statement,235,"Sorry, I still can't answer that.. Could you a...",Hi,0.117703
2,100,I am Simone,Statement,235,"Sorry, I still can't answer that.. Could you a...","Sorry, I didn't understand your question, coul...",0.575173
3,100,what is software testing,whQuestion,118,Software testing is an activity of software en...,Software testing is an activity of software en...,0.998822
4,100,what is structural testing,whQuestion,23,Structural testing (or White-Box testing) is a...,Structural testing (or White-Box testing) is a...,1.000000

In [17]:
tob[tob['v1_x_v2'] >= 0.85]

,user,question,question_class,question_cluster,answer_v1,answer_v2,v1_x_v2
index,,,,,,,
3,100,what is software testing,whQuestion,118,Software testing is an activity of software en...,Software testing is an activity of software en...,0.998822
4,100,what is structural testing,whQuestion,23,Structural testing (or White-Box testing) is a...,Structural testing (or White-Box testing) is a...,1.000000
6,100,what is system testing,whQuestion,29,System testing is a level of software testing ...,System testing is a level of software testing ...,1.000000
7,100,what is unit testing,whQuestion,136,Unit testing verifies the functioning in isola...,Unit testing verifies the functioning in isola...,1.000000
8,100,what is integration testing,whQuestion,263,Integration testing is the process of verifyin...,Integration testing is the process of verifyin...,1.000000
...,...,...,...,...,...,...,...
2971,98,comment on software testing,Statement,144,Software testing is an activity of software en...,Software testing is an activity of software en...,0.998822
2972,98,lets talk about software testing,Statement,144,Software testing is an activity of software en...,Software testing is an activity of software en...,0.998822
2976,98,Lets talk about software testing,Reject,144,Software testing is an activity of software en...,Software testing is an activity of software en...,0.998822
2979,98,what is state transitioning test,whQuestion,67,"A test, in software testing, is the act of per...","A test, in software testing, is the act of per...",1.000000
2982,98,what is state transition,whQuestion,67,"It is a criteria within functional testing, bu...","It is a criteria within functional testing, bu...",1.000000

In [9]:
# Filtering out non-relevant questions for gpt

tob[tob['question_class'] == 'Accept']

,user,question,question_class,answer_v1,answer_v2,v1_x_v2
index,,,,,,
1980,28,it s ok,Accept,I don't know how to respond this,"A test, in software testing, is the act of per...",-0.022686

In [10]:
tob[tob['question_class'] == 'Other']

,user,question,question_class,answer_v1,answer_v2,v1_x_v2
index,,,,,,
1774,224,2 + 6,Other,"Sorry, I still can't answer that.. Could you a...",Hi,0.117703
2204,49,What is 2 + 2,Other,Four.,The test set is composed by several test cases...,0.075367

In [11]:
tob[tob['question_class'] == 'Emotion']

,user,question,question_class,answer_v1,answer_v2,v1_x_v2
index,,,,,,
812,147,fail],Emotion,"Sorry, I still can't answer that.. Could you a...",I don't understand what you mean,0.325859
2344,63,hehehe,Emotion,I don't know how to respond this,Hi,0.180814

In [12]:
tob[tob['question_class'] == 'System']

,user,question,question_class,answer_v1,answer_v2,v1_x_v2
index,,,,,,
196,10,Thanks,System,You are welcome! :),No worries!,0.410182
1649,206,Thanks,System,You are welcome! :),No worries!,0.410182
2625,83,To testando,System,I don't know how to respond this,I don't understand what you mean,0.318953

In [13]:
tob[tob['question_class'] == 'Continuer']

,user,question,question_class,answer_v1,answer_v2,v1_x_v2
index,,,,,,
1038,153,difference between defect and failure,Continuer,A software defect or bug is a condition in a s...,A failure is a result of the program which is ...,0.768792
1054,153,difference between bug and bug,Continuer,A software defect or bug is a condition in a s...,"Fault is an incorrect step, process, or data d...",0.844160
1055,153,difference between defect and bug,Continuer,A software defect or bug is a condition in a s...,"Fault is an incorrect step, process, or data d...",0.844160
1512,186,What the difference between failure and error,Continuer,"Sorry, I still can't answer that.. Could you a...",An error is a state of execution of the progra...,0.058894
1513,186,What the difference between defect and error,Continuer,"Sorry, I still can't answer that.. Could you a...",An error is a state of execution of the progra...,0.058894
1526,186,What the difference between failure and error,Continuer,"Sorry, I still can't answer that.. Could you a...",An error is a state of execution of the progra...,0.058894
2547,76,difference between mistake and error,Continuer,DIFFERENCE OF mistake AND error,An error is a state of execution of the progra...,0.685000
2549,76,differences between mistake and error,Continuer,A mistake is a human action that inserts a fau...,An error is a state of execution of the progra...,0.781408
2671,89,t amo,Continuer,I don't know how to respond this,I don't understand what you mean,0.318953